services:
    base.api_exception_subscriber:
        class: BaseBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    base.api_jwt.event.authentication_success_listener:
        class: BaseBundle\Security\Authentication\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    #### Paginating (TODO: Modify to use trait)
    base.api_pagination.pagination:
        class: BaseBundle\Pagination\Pagination
        autowire: true

    #### Fractal Transformer
    base.api_transformer.abstract:
        abstract: true
        class: BaseBundle\Transformer\Transformer
        arguments: ['@router', '@doctrine.orm.entity_manager']


